FROM nginx:alpine

# remove default nginx config
RUN rm /etc/nginx/conf.d/default.conf

# add our nginx config
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

# copy vite build files
COPY dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
